name: Main build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  